### ISSUE TITLE
Error in the logs

### ISSUE THREAD

**Issue by rzup** [asbjornenge/tezos-baking-exporter#4]
Seeing this error in the logs. Any idea what could be the problem?

Baking/endorsements/balance metrics not working or not present - probably as a consequence?

invalid json response body at http://127.0.0.1:8732/chains/main/blocks/1071073/helpers/baking_rights?delegate=tz1irJKkXS2DBWkU1NnmFQx1c1L7pbGg4yhk&level=1071073&all reason: Unexpected token F in JSON at position 0
(node:15266) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'forEach' of undefined
    at Timeout.query [as _onTimeout] (/home/xtz/tezos-baking-exporter/index.js:90:16)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15266) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:15266) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I tried with wget http://127.0.0.1:8732/chains/main/blocks/1071050/helpers/baking_rights?delegate=tz1irJKkXS2DBWkU1NnmFQx1c1L7pbGg4yhk&level=1071050&all

and got this as response:

[{"level":1071051,"delegate":"tz1irJKkXS2DBWkU1NnmFQx1c1L7pbGg4yhk","priority":6,"estimated_time":"2020-08-05T13:32:30Z"}]

Thanks for this exporter - it will be super useful if I get all the metrics to work! :)) Much appreciated!

**Comment by asbjornenge** [comment]
Hey! Thanks for the kind words 😊 And sorry for my late reply...

Seems like the exporter and your wget are getting a different response 🤔 That error is typical when the request is not getting a JSON response. But the wget seems to be getting it just fine... Is the exporter and your wget calling from the same machine?

**Comment by rzup** [comment]
Solved the issue by removing "&all"  from the index.js at the end of the call and rebuilding the code.
